/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g7k7VCBKwQiRvJTKS17eAv

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsa4XhSygQxQ0I } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: a4XHSygQxQ0i/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsa4XhSygQxQ0I
});
