/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g7k7VCBKwQiRvJTKS17eAv
// Component: aJ9McLv6N_c8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: egVpduqPIsTv/component
import PersonCard from "../../PersonCard"; // plasmic-import: fL9x_oJhGbqg/component
import ServiceValue from "../../ServiceValue"; // plasmic-import: wLj9UmCNPNBB/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: KBLe6YUCIwLs/component
import FooterMain from "../../FooterMain"; // plasmic-import: hv1BGlEgV0cJ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: aJ9McLv6N_c8/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: pLW4wrcFxmib/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: moG85qpo9ZSe/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: HtOQizbO3r8R/icon

createPlasmicElementProxy;

export type PlasmicAboutUs__VariantMembers = {};
export type PlasmicAboutUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutUs__VariantsArgs;
export const PlasmicAboutUs__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutUs__ArgsType = {};
type ArgPropType = keyof PlasmicAboutUs__ArgsType;
export const PlasmicAboutUs__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutUs__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"div">;
  aboutUsBanner?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  ourTeamSection?: Flex__<"div">;
  columns?: Flex__<"div">;
  container?: Flex__<"div">;
  row1?: Flex__<"div">;
  serviceRow?: Flex__<"div">;
  homeFooterTop?: Flex__<typeof HomeFooterTop>;
  footerMain?: Flex__<typeof FooterMain>;
};

export interface DefaultAboutUsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutUs__RenderFunc(props: {
  variants: PlasmicAboutUs__VariantsArgs;
  args: PlasmicAboutUs__ArgsType;
  overrides: PlasmicAboutUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicAboutUs.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <Header
              className={classNames("__wab_instance", sty.header__j4OKr)}
            />
          </div>
          <div
            data-plasmic-name={"aboutUsBanner"}
            data-plasmic-override={overrides.aboutUsBanner}
            className={classNames(projectcss.all, sty.aboutUsBanner)}
          >
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__aMwVq)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"About Us"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ls80K
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                  }
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"ourTeamSection"}
            data-plasmic-override={overrides.ourTeamSection}
            className={classNames(projectcss.all, sty.ourTeamSection)}
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__gEgQu)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__htKc0
                  )}
                >
                  {"Our team"}
                </h2>
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <div
                    data-plasmic-name={"row1"}
                    data-plasmic-override={overrides.row1}
                    className={classNames(projectcss.all, sty.row1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__p3B7J)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__aGxD
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/team4Jpg.jpg",
                          fullWidth: 370,
                          fullHeight: 450,
                          aspectRatio: undefined
                        }}
                        slot={"Job title"}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___7HpVu
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__mghsy)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__rvWZ
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/tm1Jpg.jpg",
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__l0TfC
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__eRMr)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__z3VYa
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/team2Jpg3.jpg",
                          fullWidth: 370,
                          fullHeight: 450,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__bAcwJ
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__gy4Si)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard___9D6C1
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/images1Jpg.jpg",
                          fullWidth: 225,
                          fullHeight: 225,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__p0Bl5
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__igMo8)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__gJs81
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/avatar3Png.png",
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__iX3Rt
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__rQiF)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard___7FNj
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/unnamedJpg.jpg",
                          fullWidth: 370,
                          fullHeight: 411,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__kfF8P
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___99M06)}>
            <div className={classNames(projectcss.all, sty.freeBox__tRq7)}>
              <div className={classNames(projectcss.all, sty.freeBox__bMc4W)}>
                <div className={classNames(projectcss.all, sty.freeBox__ejpeY)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__z8Axy
                    )}
                  >
                    {"Our values"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9PesB
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__q4Vla)}>
                  <div
                    data-plasmic-name={"serviceRow"}
                    data-plasmic-override={overrides.serviceRow}
                    className={classNames(projectcss.all, sty.serviceRow)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__l4WXb)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__cHxgZ
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__vz4Pt
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___2XcHl)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__paRpC
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___6OlGk
                          )}
                        >
                          {"Service"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__gGj1T)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__hDp6J
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__u53Tm
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__mshKq)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__joHiH
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___6Z6D
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__o2Dvs)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__wRfsl
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__i9VlA
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qCfHv)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue___7MXxv
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__e155K
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__w1Sg)}>
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "aboutUsBanner",
    "foreground2",
    "h1",
    "ourTeamSection",
    "columns",
    "container",
    "row1",
    "serviceRow",
    "homeFooterTop",
    "footerMain"
  ],
  header: ["header"],
  aboutUsBanner: ["aboutUsBanner", "foreground2", "h1"],
  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  ourTeamSection: ["ourTeamSection", "columns", "container", "row1"],
  columns: ["columns", "container", "row1"],
  container: ["container", "row1"],
  row1: ["row1"],
  serviceRow: ["serviceRow"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "div";
  aboutUsBanner: "div";
  foreground2: "div";
  h1: "h1";
  ourTeamSection: "div";
  columns: "div";
  container: "div";
  row1: "div";
  serviceRow: "div";
  homeFooterTop: typeof HomeFooterTop;
  footerMain: typeof FooterMain;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutUs__VariantsArgs;
    args?: PlasmicAboutUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAboutUs__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAboutUs__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    aboutUsBanner: makeNodeComponent("aboutUsBanner"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    ourTeamSection: makeNodeComponent("ourTeamSection"),
    columns: makeNodeComponent("columns"),
    container: makeNodeComponent("container"),
    row1: makeNodeComponent("row1"),
    serviceRow: makeNodeComponent("serviceRow"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),

    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "About Us",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
