/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g7k7VCBKwQiRvJTKS17eAv
// Component: 0OuU0_rXnkiZ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: egVpduqPIsTv/component
import Client from "../../Client"; // plasmic-import: BRr3EwkT6wQs/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: KBLe6YUCIwLs/component
import FooterMain from "../../FooterMain"; // plasmic-import: hv1BGlEgV0cJ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectcss
import sty from "./PlasmicClients.module.css"; // plasmic-import: 0OuU0_rXnkiZ/css

createPlasmicElementProxy;

export type PlasmicClients__VariantMembers = {};
export type PlasmicClients__VariantsArgs = {};
type VariantPropType = keyof PlasmicClients__VariantsArgs;
export const PlasmicClients__VariantProps = new Array<VariantPropType>();

export type PlasmicClients__ArgsType = {};
type ArgPropType = keyof PlasmicClients__ArgsType;
export const PlasmicClients__ArgProps = new Array<ArgPropType>();

export type PlasmicClients__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  banner?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  text?: Flex__<"div">;
  clientsSection5?: Flex__<"div">;
  footerTopSection?: Flex__<"div">;
  homeFooterTop?: Flex__<typeof HomeFooterTop>;
  footerMain?: Flex__<typeof FooterMain>;
};

export interface DefaultClientsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicClients__RenderFunc(props: {
  variants: PlasmicClients__VariantsArgs;
  args: PlasmicClients__ArgsType;
  overrides: PlasmicClients__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicClients.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicClients.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicClients.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"banner"}
            data-plasmic-override={overrides.banner}
            className={classNames(projectcss.all, sty.banner)}
          >
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__v2FrR)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Clients"}
                </h1>
                <div
                  data-plasmic-name={"text"}
                  data-plasmic-override={overrides.text}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting "
                  }
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__jhsOs)}>
            <div className={classNames(projectcss.all, sty.columns__bmzi8)}>
              <div className={classNames(projectcss.all, sty.column__ku7Mi)}>
                <div className={classNames(projectcss.all, sty.freeBox__s44TZ)}>
                  <div
                    className={classNames(projectcss.all, sty.columns___4TWc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__iixaO)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client__o0HPc
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__d3Uef
                          )}
                        >
                          {"Client name"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___498Fe)}>
                <div className={classNames(projectcss.all, sty.freeBox__tSMbv)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__x2VOv)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__wjz5M)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client__lZuk7
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2___3Omku
                          )}
                        >
                          {"Client name 2"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__wPszn)}>
                <div className={classNames(projectcss.all, sty.freeBox__ga0N)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__jq309)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__zi2GN)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client__mkmsC
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__dAHzp
                          )}
                        >
                          {"Client name"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__b71J)}>
                <div className={classNames(projectcss.all, sty.freeBox__cmhwk)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__uwpWw)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___1Tlav)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client___5EEm3
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__mlIa1
                          )}
                        >
                          {"Client name"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"clientsSection5"}
            data-plasmic-override={overrides.clientsSection5}
            className={classNames(projectcss.all, sty.clientsSection5)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___376M5)}>
              <div className={classNames(projectcss.all, sty.columns__okUmG)}>
                <div className={classNames(projectcss.all, sty.column__jq2DK)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__q2PpJ
                    )}
                  >
                    {"More client's we've worked with"}
                  </h2>
                </div>
                <div className={classNames(projectcss.all, sty.column__wAb5J)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nNet6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hxYCa)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__rwnqZ)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/agency_website/images/airbnbSvg.svg",
                          fullWidth: 300,
                          fullHeight: 96,
                          aspectRatio: 3.125
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__myhmo)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/agency_website/images/asanaSvg.svg",
                          fullWidth: 300,
                          fullHeight: 62,
                          aspectRatio: 4.863636
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__s1Qmt)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/agency_website/images/disneySvg.svg",
                          fullWidth: 300,
                          fullHeight: 124,
                          aspectRatio: 2.41655
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__nVicv)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/agency_website/images/instacartSvg.svg",
                          fullWidth: 300,
                          fullHeight: 60,
                          aspectRatio: 4.961538
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"footerTopSection"}
            data-plasmic-override={overrides.footerTopSection}
            className={classNames(projectcss.all, sty.footerTopSection)}
          >
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "banner",
    "foreground2",
    "h1",
    "text",
    "clientsSection5",
    "footerTopSection",
    "homeFooterTop",
    "footerMain"
  ],
  header: ["header"],
  banner: ["banner", "foreground2", "h1", "text"],
  foreground2: ["foreground2", "h1", "text"],
  h1: ["h1"],
  text: ["text"],
  clientsSection5: ["clientsSection5"],
  footerTopSection: ["footerTopSection", "homeFooterTop"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  banner: "div";
  foreground2: "div";
  h1: "h1";
  text: "div";
  clientsSection5: "div";
  footerTopSection: "div";
  homeFooterTop: typeof HomeFooterTop;
  footerMain: typeof FooterMain;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicClients__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicClients__VariantsArgs;
    args?: PlasmicClients__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicClients__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicClients__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicClients__ArgProps,
          internalVariantPropNames: PlasmicClients__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicClients__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicClients";
  } else {
    func.displayName = `PlasmicClients.${nodeName}`;
  }
  return func;
}

export const PlasmicClients = Object.assign(
  // Top-level PlasmicClients renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    banner: makeNodeComponent("banner"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    text: makeNodeComponent("text"),
    clientsSection5: makeNodeComponent("clientsSection5"),
    footerTopSection: makeNodeComponent("footerTopSection"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),

    // Metadata about props expected for PlasmicClients
    internalVariantProps: PlasmicClients__VariantProps,
    internalArgProps: PlasmicClients__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Clients",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicClients;
/* prettier-ignore-end */
