/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g7k7VCBKwQiRvJTKS17eAv
// Component: khB95mNLurUN

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: egVpduqPIsTv/component
import ServiceWhite from "../../ServiceWhite"; // plasmic-import: mApax7JlNwjt/component
import BlueBdr from "../../BlueBdr"; // plasmic-import: d-BgVkXqm7qV/component
import ServiceDark from "../../ServiceDark"; // plasmic-import: 3vzt3YMSWVMq/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: KBLe6YUCIwLs/component
import FooterMain from "../../FooterMain"; // plasmic-import: hv1BGlEgV0cJ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectcss
import sty from "./PlasmicServices.module.css"; // plasmic-import: khB95mNLurUN/css

createPlasmicElementProxy;

export type PlasmicServices__VariantMembers = {};
export type PlasmicServices__VariantsArgs = {};
type VariantPropType = keyof PlasmicServices__VariantsArgs;
export const PlasmicServices__VariantProps = new Array<VariantPropType>();

export type PlasmicServices__ArgsType = {};
type ArgPropType = keyof PlasmicServices__ArgsType;
export const PlasmicServices__ArgProps = new Array<ArgPropType>();

export type PlasmicServices__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  aboutUsBanner?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  serviceRow?: Flex__<"div">;
  serviceRow2?: Flex__<"div">;
  serviceRow3?: Flex__<"div">;
  footerTopSection?: Flex__<"div">;
  homeFooterTop?: Flex__<typeof HomeFooterTop>;
  footerMain?: Flex__<typeof FooterMain>;
};

export interface DefaultServicesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicServices__RenderFunc(props: {
  variants: PlasmicServices__VariantsArgs;
  args: PlasmicServices__ArgsType;
  overrides: PlasmicServices__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicServices.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicServices.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicServices.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"aboutUsBanner"}
            data-plasmic-override={overrides.aboutUsBanner}
            className={classNames(projectcss.all, sty.aboutUsBanner)}
          >
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__jde7Z)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Services"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lCAxU
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Lorem Ipsum is simply dummy text of the printing and typesetting indstandard dummy text ever since the 1500s."
                    : "Lorem Ipsum is simply dummy text of the printing and typesetting indstandard dummy text ever since the 1500s."}
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__pyKlr)}>
            <div className={classNames(projectcss.all, sty.freeBox__ve988)}>
              <div className={classNames(projectcss.all, sty.freeBox__uv3Je)}>
                <div className={classNames(projectcss.all, sty.freeBox__oneCx)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__vwphC
                    )}
                  >
                    {"Service type"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hoXbG
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__gvdb)}>
                  <div
                    data-plasmic-name={"serviceRow"}
                    data-plasmic-override={overrides.serviceRow}
                    className={classNames(projectcss.all, sty.serviceRow)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___75Fii)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__rmSbG
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__nn4Ur
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qhAc0)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite___6DFuM
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__rQhf1
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__pygqg)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__i154S
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__pxNpo
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___5EJyf)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__krnLr
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__vBo50
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___4Vxrj)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__ksgE
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__sPoqB
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hyNl)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__irKcQ
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__qgYhl
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__bGiQe)}>
            <div className={classNames(projectcss.all, sty.freeBox__otCl4)}>
              <div className={classNames(projectcss.all, sty.freeBox__kYbZl)}>
                <div className={classNames(projectcss.all, sty.freeBox__j9WEo)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ogGz6
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Service category"
                      : "Service type"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r5Ot2
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy"
                    }
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0A4YD)}
                >
                  <div
                    data-plasmic-name={"serviceRow2"}
                    data-plasmic-override={overrides.serviceRow2}
                    className={classNames(projectcss.all, sty.serviceRow2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__z2WBz)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark___9AozX
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___9I24U)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__x2V8J
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cWqvm
                          )}
                        >
                          {"Service name 3"}
                        </div>
                      </ServiceDark>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ppIv)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__xiiLw
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__uRWmp)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__xoe2
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__azFxu)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark___0Wemr
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hqG1Y)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__y7I0C
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                        }
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__loo17)}>
            <div className={classNames(projectcss.all, sty.freeBox__h2JpE)}>
              <div className={classNames(projectcss.all, sty.freeBox__exzoS)}>
                <div className={classNames(projectcss.all, sty.freeBox__wRYfi)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__kj4Q
                    )}
                  >
                    {"Service type"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vfTt
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yBvj)}>
                  <div
                    data-plasmic-name={"serviceRow3"}
                    data-plasmic-override={overrides.serviceRow3}
                    className={classNames(projectcss.all, sty.serviceRow3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__dtAvW)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite___5Qq3Y
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__slnUz
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qzOkD)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__fB0H
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__w1Anc
                          )}
                        >
                          {"Services 2"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__okygv)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__arIfc
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__af8YM
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ryQgm)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__awZtr
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__qs306
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___1IMoQ)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__ztPsw
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__x9B
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__v0XsI)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__sjA1
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__sqUjE
                          )}
                        >
                          {"Service name"}
                        </h3>
                      </ServiceWhite>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"footerTopSection"}
            data-plasmic-override={overrides.footerTopSection}
            className={classNames(projectcss.all, sty.footerTopSection)}
          >
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "aboutUsBanner",
    "foreground2",
    "h1",
    "serviceRow",
    "serviceRow2",
    "serviceRow3",
    "footerTopSection",
    "homeFooterTop",
    "footerMain"
  ],
  header: ["header"],
  aboutUsBanner: ["aboutUsBanner", "foreground2", "h1"],
  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  serviceRow: ["serviceRow"],
  serviceRow2: ["serviceRow2"],
  serviceRow3: ["serviceRow3"],
  footerTopSection: ["footerTopSection", "homeFooterTop"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  aboutUsBanner: "div";
  foreground2: "div";
  h1: "h1";
  serviceRow: "div";
  serviceRow2: "div";
  serviceRow3: "div";
  footerTopSection: "div";
  homeFooterTop: typeof HomeFooterTop;
  footerMain: typeof FooterMain;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicServices__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicServices__VariantsArgs;
    args?: PlasmicServices__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicServices__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicServices__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicServices__ArgProps,
          internalVariantPropNames: PlasmicServices__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    aboutUsBanner: makeNodeComponent("aboutUsBanner"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    serviceRow: makeNodeComponent("serviceRow"),
    serviceRow2: makeNodeComponent("serviceRow2"),
    serviceRow3: makeNodeComponent("serviceRow3"),
    footerTopSection: makeNodeComponent("footerTopSection"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),

    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Service",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
