/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g7k7VCBKwQiRvJTKS17eAv
// Component: aR_XJnyDRpY7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: g7k7VCBKwQiRvJTKS17eAv/projectcss
import sty from "./PlasmicSocialIcons.module.css"; // plasmic-import: aR_XJnyDRpY7/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: pLW4wrcFxmib/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: moG85qpo9ZSe/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: HtOQizbO3r8R/icon

createPlasmicElementProxy;

export type PlasmicSocialIcons__VariantMembers = {};
export type PlasmicSocialIcons__VariantsArgs = {};
type VariantPropType = keyof PlasmicSocialIcons__VariantsArgs;
export const PlasmicSocialIcons__VariantProps = new Array<VariantPropType>();

export type PlasmicSocialIcons__ArgsType = {};
type ArgPropType = keyof PlasmicSocialIcons__ArgsType;
export const PlasmicSocialIcons__ArgProps = new Array<ArgPropType>();

export type PlasmicSocialIcons__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultSocialIconsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSocialIcons__RenderFunc(props: {
  variants: PlasmicSocialIcons__VariantsArgs;
  args: PlasmicSocialIcons__ArgsType;
  overrides: PlasmicSocialIcons__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <IconIcon
        className={classNames(projectcss.all, sty.svg__ziuJh)}
        href={"https://www.linkedin.com/"}
        link={"https://www.linkedin.com/"}
        role={"img"}
      />

      <Icon2Icon
        className={classNames(projectcss.all, sty.svg__j6AWu)}
        role={"img"}
      />

      <Icon3Icon
        className={classNames(projectcss.all, sty.svg__ue93B)}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSocialIcons__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSocialIcons__VariantsArgs;
    args?: PlasmicSocialIcons__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSocialIcons__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSocialIcons__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSocialIcons__ArgProps,
          internalVariantPropNames: PlasmicSocialIcons__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSocialIcons__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSocialIcons";
  } else {
    func.displayName = `PlasmicSocialIcons.${nodeName}`;
  }
  return func;
}

export const PlasmicSocialIcons = Object.assign(
  // Top-level PlasmicSocialIcons renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSocialIcons
    internalVariantProps: PlasmicSocialIcons__VariantProps,
    internalArgProps: PlasmicSocialIcons__ArgProps
  }
);

export default PlasmicSocialIcons;
/* prettier-ignore-end */
